/**
 * Minimal flow example: register, use, and release a database through DbManager.
 *
 * Covered steps:
 * 1. Register the shared PostgreSQL configuration with DbManager.addDatabase.
 * 2. Retrieve a connector via DbManager.getConnector.
 * 3. Insert a record into minimal_app.item without providing the primary key.
 * 4. Read and display the stored records.
 * 5. Release resources by closing the connector and invoking DbManager.removeDatabase.
 */

import { DbManager } from './app/db/DbManager.js';
import { Log } from './app/Log.js';



// Step 1: set the log level to display informational messages during the workflow.
Log.setMode('info');

// Step 2: register the shared PostgreSQL configuration.
DbManager.addDatabase(
{
    host: 'localhost',
    port: 5432,
    user: 'appcore',
    password: 'appcore',
    database: 'appcore',
    ssl: false
});

// Step 3: retrieve a connector to execute SQL statements.
const connector = DbManager.getConnector('appcore');

// Step 4: insert a row without providing the primary key (generated by the database).
const itemLabel = `Exemple ${new Date().toISOString()}`;
await connector.query(
    'INSERT INTO minimal_app.item (name) VALUES ($1) RETURNING id, name;',
    [itemLabel]
);
const insertedItem = await connector.next();
Log.info('Inserted item:', insertedItem);


// Step 5: read the entire table to confirm the new row is stored.
await connector.query('SELECT id, name FROM minimal_app.item ORDER BY id ASC;');
const storedItems = [];
let currentRow = await connector.next();

while (currentRow)
{
    storedItems.push(currentRow);
    currentRow = await connector.next();
}

Log.info('Stored items:',storedItems);

// Step 6: release resources by closing the connector and removing the database.
connector.close();
await DbManager.removeDatabase('appcore');
