/**
 * Minimal flow example: register, use, and release a database through DbManager.
 *
 * Covered steps:
 * 1. Register the shared PostgreSQL configuration with DbManager.addDatabase.
 * 2. Retrieve a connector via DbManager.getConnector.
 * 3. Insert a record into minimal_app.item without providing the primary key.
 * 4. Read and display the stored records.
 * 5. Release resources by closing the connector and invoking DbManager.removeDatabase.
 */

import { DbManager } from './app/db/DbManager.js';
import { Log } from './app/Log.js';



// Step 1: set the log level to display informational messages during the workflow.
Log.setMode('info');

// Step 2: register the shared PostgreSQL configuration.
DbManager.addDatabase(
{
    host: 'localhost',
    port: 5432,
    user: 'appcore',
    password: 'appcore',
    database: 'appcore'
});
// Step 3: retrieve a connector to execute SQL statements.
const connector = DbManager.getConnector('appcore');

// Step 4-1: insert a row without providing the primary key
// (it is generated by the database) using an explicit schema name prefix.
await connector.query('INSERT INTO minimal_app.item (name) VALUES ($1)', ['Alice Smith']);

// Step 4-2: insert rows using the schema search_path
// (it remains active for the current connection).
await connector.query('SET search_path TO minimal_app;');
await connector.query('INSERT INTO item (name) VALUES ($1)', ['Bob Johnson']);
await connector.query('INSERT INTO item (name) VALUES ($1)', ['Acme Corp']);

// You can also use ALTER ROLE or ALTER DATABASE
// to configure the search_path more persistently.

// Step 5: read the entire table to confirm the new rows are stored.
await connector.query('SELECT * FROM item');

let row = await connector.next();
while (row)
{
    Log.info(row);
    row = await connector.next();
}


// Step 6: release resources by closing the connector and removing the database.
connector.close();
await DbManager.removeDatabase('appcore');
