services:
  postgres:
    image: postgres:18
    container_name: appcore-example-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appcore
      POSTGRES_PASSWORD: appcore
      POSTGRES_DB: appcore
    ports:
      - "5432:5432"
    volumes:
      - app-core-data:/var/lib/postgresql
      - ./:/examples:ro

volumes:
  app-core-data:
    driver: local