services:
  postgres:
    image: postgres:18
    container_name: appcore-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appcore
      POSTGRES_PASSWORD: appcore
      POSTGRES_DB: appcore
    ports:
      - "5433:5432"
    volumes:
      - app-core:/var/lib/postgresql
      - ./:/scripts:ro

volumes:
  app-core:
    driver: local